# This workflow accepts a secret and prints the length of its value. There's
# nothing special about what happens here, but the calling workflows
# demonstrate the capability to dynamically select a secret to be passed to a
# reusable workflow.
name: Accept Dynamic Secret
on:
  workflow_call:
    inputs:
      dynamic-secret-name:
        description: The name of the secret whose value is passed to secrts.dynamic-secret-value
        required: true
        type: string
    secrets:
      dynamic-secret-value:
        description: The value of the dynamically-passed secret
        required: true
jobs:
  print-dynamic-secret-name-and-length:
    name: Print Dynamic Secret Name And Length
    runs-on: ubuntu-latest
    steps:
      - name: Print Dynamic Secret Name And Length
        run: echo "The value of the secret '${{ inputs.dynamic-secret-name }}' contains $(echo -n ${{ secrets.dynamic-secret-value }} | wc -c) characters."
