# This workflow passes a secret into the env context, then runs a script that
# passes the secret as a CLI argument using a runtime reference to the environment
# variable ${SECRET}. Even with set -x in the script, GitHub knows to mask the
# value of the secret from the output.
name: Pass Secret On CLI Using Env Reference
on: [push]
jobs:
  pass-secret-on-cli-via-env-ref:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.NOT_REALLY_A_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/wc-secret-env-var.sh
