# This workflow calls a reusable workflow in a matrix, passing secrets that
# were dynamically selected from the output of another job.
name: Pass Dynamically Selected Secrets To Reusable Workflow
on: [push]
jobs:
  get-dynamic-secret-names:
    name: Get Dynamic Secret Names
    runs-on: ubuntu-latest
    outputs:
      dynamic-secret-names: ${{ steps.get-dynamic-secret-names.outputs.dynamic-secret-names }}
    steps:
      - id: get-dynamic-secret-names
        name: Get Dynamic Secret Names
        run: |
          echo "dynamic-secret-names=['DYNAMIC_SECRET_WITH_LEN_8', 'DYNAMIC_SECRET_WITH_LEN_13', 'DYNAMIC_SECRET_WITH_LEN_21']" >> $GITHUB_OUTPUT
  pass-dynamic-secret:
    uses: ./.github/workflows/accept-dynamic-secret.yml
    needs:
      - get-dynamic-secret-names
    strategy:
      max-parallel: 10
      fail-fast: true
      matrix:
        dynamic-secret-name: ${{ fromJson(needs.get-dynamic-secret-names.outputs.dynamic-secret-names) }}
    name: Accept Dynamic Secret (${{ matrix.dynamic-secret-name }})
    with:
      dynamic-secret-name: ${{ matrix.dynamic-secret-name }}
    secrets:
      dynamic-secret-value: ${{ secrets[matrix.dynamic-secret-name] }}
