# This workflow puts a secret in the env context, then a script uses the env var
# as a CLI argument.
name: Pass Secret On CLI Using Env Reference
on: [push]
jobs:
  pass-secret-on-cli-via-env-ref:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.NOT_REALLY_A_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/wc-secret-env-var.sh
